/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_COLON = 1,
  anon_sym_LF = 2,
  anon_sym_LBRACK_LBRACK = 3,
  anon_sym_RBRACK_RBRACK = 4,
  anon_sym_LBRACKimg_LBRACK = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  aux_sym__json_part_token1 = 10,
  aux_sym__inline_json_part_token1 = 11,
  anon_sym_LT_LT = 12,
  anon_sym_SLASH = 13,
  anon_sym_GT_GT = 14,
  sym_macro_name = 15,
  aux_sym_macro_body_token1 = 16,
  aux_sym_macro_body_token2 = 17,
  anon_sym_GT = 18,
  anon_sym_QMARK = 19,
  sym_variable = 20,
  aux_sym_string_token1 = 21,
  aux_sym_string_token2 = 22,
  aux_sym_string_token3 = 23,
  sym_keyword_op = 24,
  sym__macro_word = 25,
  sym_number = 26,
  sym_comment = 27,
  sym_tag_name = 28,
  sym_attributes = 29,
  sym_plain_text = 30,
  sym_separator = 31,
  sym_label = 32,
  sym_name = 33,
  sym_dest = 34,
  sym_tag = 35,
  sym_story = 36,
  sym_passage = 37,
  sym__body = 38,
  sym_prose = 39,
  sym__prose_part = 40,
  sym_heading = 41,
  sym_link = 42,
  sym_image_link = 43,
  sym_tags = 44,
  sym_json = 45,
  aux_sym__json_part = 46,
  sym_inline_json = 47,
  aux_sym__inline_json_part = 48,
  sym_macro = 49,
  sym_macro_body = 50,
  sym_string = 51,
  sym_html_tag = 52,
  aux_sym_story_repeat1 = 53,
  aux_sym_prose_repeat1 = 54,
  aux_sym_tags_repeat1 = 55,
  aux_sym_macro_body_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_LF] = "\n",
  [anon_sym_LBRACK_LBRACK] = "[[",
  [anon_sym_RBRACK_RBRACK] = "]]",
  [anon_sym_LBRACKimg_LBRACK] = "[img[",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__json_part_token1] = "_json_part_token1",
  [aux_sym__inline_json_part_token1] = "_inline_json_part_token1",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT_GT] = ">>",
  [sym_macro_name] = "macro_name",
  [aux_sym_macro_body_token1] = "macro_body_token1",
  [aux_sym_macro_body_token2] = "macro_body_token2",
  [anon_sym_GT] = ">",
  [anon_sym_QMARK] = "\?",
  [sym_variable] = "variable",
  [aux_sym_string_token1] = "string_token1",
  [aux_sym_string_token2] = "string_token2",
  [aux_sym_string_token3] = "string_token3",
  [sym_keyword_op] = "keyword_op",
  [sym__macro_word] = "_macro_word",
  [sym_number] = "number",
  [sym_comment] = "comment",
  [sym_tag_name] = "tag_name",
  [sym_attributes] = "attributes",
  [sym_plain_text] = "plain_text",
  [sym_separator] = "separator",
  [sym_label] = "label",
  [sym_name] = "name",
  [sym_dest] = "dest",
  [sym_tag] = "tag",
  [sym_story] = "story",
  [sym_passage] = "passage",
  [sym__body] = "_body",
  [sym_prose] = "prose",
  [sym__prose_part] = "_prose_part",
  [sym_heading] = "heading",
  [sym_link] = "link",
  [sym_image_link] = "image_link",
  [sym_tags] = "tags",
  [sym_json] = "json",
  [aux_sym__json_part] = "_json_part",
  [sym_inline_json] = "inline_json",
  [aux_sym__inline_json_part] = "_inline_json_part",
  [sym_macro] = "macro",
  [sym_macro_body] = "macro_body",
  [sym_string] = "string",
  [sym_html_tag] = "html_tag",
  [aux_sym_story_repeat1] = "story_repeat1",
  [aux_sym_prose_repeat1] = "prose_repeat1",
  [aux_sym_tags_repeat1] = "tags_repeat1",
  [aux_sym_macro_body_repeat1] = "macro_body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_LBRACK_LBRACK] = anon_sym_LBRACK_LBRACK,
  [anon_sym_RBRACK_RBRACK] = anon_sym_RBRACK_RBRACK,
  [anon_sym_LBRACKimg_LBRACK] = anon_sym_LBRACKimg_LBRACK,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__json_part_token1] = aux_sym__json_part_token1,
  [aux_sym__inline_json_part_token1] = aux_sym__inline_json_part_token1,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_macro_name] = sym_macro_name,
  [aux_sym_macro_body_token1] = aux_sym_macro_body_token1,
  [aux_sym_macro_body_token2] = aux_sym_macro_body_token2,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [sym_variable] = sym_variable,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [aux_sym_string_token3] = aux_sym_string_token3,
  [sym_keyword_op] = sym_keyword_op,
  [sym__macro_word] = sym__macro_word,
  [sym_number] = sym_number,
  [sym_comment] = sym_comment,
  [sym_tag_name] = sym_tag_name,
  [sym_attributes] = sym_attributes,
  [sym_plain_text] = sym_plain_text,
  [sym_separator] = sym_separator,
  [sym_label] = sym_label,
  [sym_name] = sym_name,
  [sym_dest] = sym_dest,
  [sym_tag] = sym_tag,
  [sym_story] = sym_story,
  [sym_passage] = sym_passage,
  [sym__body] = sym__body,
  [sym_prose] = sym_prose,
  [sym__prose_part] = sym__prose_part,
  [sym_heading] = sym_heading,
  [sym_link] = sym_link,
  [sym_image_link] = sym_image_link,
  [sym_tags] = sym_tags,
  [sym_json] = sym_json,
  [aux_sym__json_part] = aux_sym__json_part,
  [sym_inline_json] = sym_inline_json,
  [aux_sym__inline_json_part] = aux_sym__inline_json_part,
  [sym_macro] = sym_macro,
  [sym_macro_body] = sym_macro_body,
  [sym_string] = sym_string,
  [sym_html_tag] = sym_html_tag,
  [aux_sym_story_repeat1] = aux_sym_story_repeat1,
  [aux_sym_prose_repeat1] = aux_sym_prose_repeat1,
  [aux_sym_tags_repeat1] = aux_sym_tags_repeat1,
  [aux_sym_macro_body_repeat1] = aux_sym_macro_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACKimg_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__json_part_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inline_json_part_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_macro_body_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_body_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_keyword_op] = {
    .visible = true,
    .named = true,
  },
  [sym__macro_word] = {
    .visible = false,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_text] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_dest] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_story] = {
    .visible = true,
    .named = true,
  },
  [sym_passage] = {
    .visible = true,
    .named = true,
  },
  [sym__body] = {
    .visible = false,
    .named = true,
  },
  [sym_prose] = {
    .visible = true,
    .named = true,
  },
  [sym__prose_part] = {
    .visible = false,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_link] = {
    .visible = true,
    .named = true,
  },
  [sym_image_link] = {
    .visible = true,
    .named = true,
  },
  [sym_tags] = {
    .visible = true,
    .named = true,
  },
  [sym_json] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__json_part] = {
    .visible = false,
    .named = false,
  },
  [sym_inline_json] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_json_part] = {
    .visible = false,
    .named = false,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_body] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_html_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_story_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prose_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tags_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '"', 13,
        '$', 39,
        '\'', 15,
        '/', 63,
        ':', 27,
        '<', 11,
        '>', 72,
        '?', 73,
        '[', 52,
        ']', 54,
        '_', 101,
        '`', 33,
        'a', 94,
        'e', 96,
        'g', 100,
        'i', 98,
        'l', 100,
        'n', 93,
        'o', 97,
        't', 95,
        '{', 55,
        '}', 56,
        '-', 65,
        '=', 65,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      if (('b' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(103);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 110,
        '/', 113,
        '<', 112,
        '[', 115,
        '{', 55,
        '$', 116,
        '?', 116,
        '_', 116,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(117);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '[') ADVANCE(51);
      if (lookahead == '{') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(3);
      if (lookahead == '{') ADVANCE(55);
      if (lookahead == '}') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 4:
      if (lookahead == '\n') SKIP(37);
      if (lookahead == ' ') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(122);
      END_STATE();
    case 5:
      if (lookahead == ' ') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(124);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(124);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(124);
      END_STATE();
    case 8:
      if (lookahead == ' ') SKIP(8);
      if (lookahead == '>') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(120);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '>') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(120);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(122);
      END_STATE();
    case 11:
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '<') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 12:
      ADVANCE_MAP(
        '"', 13,
        '$', 39,
        '\'', 15,
        '-', 67,
        '>', 72,
        '?', 73,
        '_', 101,
        '`', 33,
        'a', 84,
        'e', 86,
        'g', 90,
        'i', 88,
        'l', 90,
        'n', 83,
        'o', 87,
        't', 85,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 13:
      if (lookahead == '"') ADVANCE(75);
      if (lookahead == '\\') ADVANCE(40);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '%') ADVANCE(24);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '\'') ADVANCE(76);
      if (lookahead == '\\') ADVANCE(41);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '*') ADVANCE(25);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(23);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(28);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '<') ADVANCE(20);
      if (lookahead == '>') ADVANCE(71);
      if (lookahead == ']') ADVANCE(53);
      if (lookahead == '|') ADVANCE(118);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(118);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == ' ' ||
          lookahead == '>') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(120);
      END_STATE();
    case 22:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 23:
      if (lookahead == '-') ADVANCE(18);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 24:
      if (lookahead == '/') ADVANCE(106);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 25:
      if (lookahead == '/') ADVANCE(106);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == '/') ADVANCE(62);
      if (lookahead == ']') ADVANCE(32);
      if (lookahead == '-' ||
          lookahead == '=') ADVANCE(65);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 27:
      if (lookahead == ':') ADVANCE(46);
      END_STATE();
    case 28:
      if (lookahead == '>') ADVANCE(106);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == '>') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 30:
      if (lookahead == '>') ADVANCE(118);
      END_STATE();
    case 31:
      if (lookahead == '[') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == ']') ADVANCE(49);
      END_STATE();
    case 33:
      if (lookahead == '`') ADVANCE(77);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 34:
      if (lookahead == 'g') ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 36:
      if (lookahead == '{') ADVANCE(55);
      if (lookahead == '}') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 37:
      if (lookahead == '\n' ||
          lookahead == ' ') SKIP(37);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(122);
      END_STATE();
    case 38:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 39:
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 40:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 41:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(15);
      END_STATE();
    case 42:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(21);
      END_STATE();
    case 43:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(21);
      END_STATE();
    case 44:
      if (eof) ADVANCE(45);
      ADVANCE_MAP(
        '\n', 111,
        '/', 113,
        ':', 114,
        '<', 112,
        '[', 115,
        '$', 116,
        '?', 116,
        '_', 116,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0) ADVANCE(117);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACK_LBRACK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACK_RBRACK);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACKimg_LBRACK);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '[') ADVANCE(48);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      if (lookahead == ']') ADVANCE(49);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym__json_part_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym__json_part_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym__inline_json_part_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym__inline_json_part_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '%') ADVANCE(14);
      if (lookahead == '*') ADVANCE(16);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_macro_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_macro_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_macro_body_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\'' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(69);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(aux_sym_macro_body_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\'' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_macro_body_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\'' &&
          lookahead != '>' &&
          lookahead != '?' &&
          lookahead != '_' &&
          lookahead != '`') ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_macro_body_token2);
      ADVANCE_MAP(
        '-', 67,
        '_', 101,
        'a', 84,
        'e', 86,
        'g', 90,
        'i', 88,
        'l', 90,
        'n', 83,
        'o', 87,
        't', 85,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_QMARK);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_string_token3);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_keyword_op);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'e') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_keyword_op);
      if (lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_keyword_op);
      if (lookahead == 'e') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_keyword_op);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'd') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'e') ADVANCE(79);
      if (lookahead == 'o') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'n') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'o') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'q') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 'r') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 's') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 't') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (lookahead == 't') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 'd') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 'e') ADVANCE(81);
      if (lookahead == 'o') ADVANCE(99);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 'n') ADVANCE(92);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 'o') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 'q') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 'r') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 's') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 't') ADVANCE(81);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym__macro_word);
      if (lookahead == 't') ADVANCE(80);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__macro_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(103);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__macro_word);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym__macro_word);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_attributes);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(109);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_attributes);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_plain_text);
      ADVANCE_MAP(
        '\n', 110,
        '/', 113,
        '<', 112,
        '[', 115,
        '{', 55,
        '$', 116,
        '?', 116,
        '_', 116,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0) ADVANCE(117);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_plain_text);
      ADVANCE_MAP(
        '\n', 111,
        '/', 113,
        ':', 114,
        '<', 112,
        '[', 115,
        '$', 116,
        '?', 116,
        '_', 116,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0) ADVANCE(117);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_plain_text);
      if (lookahead == '!') ADVANCE(22);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead == '<') ADVANCE(61);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_plain_text);
      if (lookahead == '%') ADVANCE(14);
      if (lookahead == '*') ADVANCE(16);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_plain_text);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '$' &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '?' &&
          lookahead != '[' &&
          lookahead != '_') ADVANCE(117);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_plain_text);
      if (lookahead == '[') ADVANCE(48);
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_plain_text);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_plain_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '$' &&
          lookahead != '/' &&
          lookahead != '<' &&
          lookahead != '?' &&
          lookahead != '[' &&
          lookahead != '_') ADVANCE(117);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_label);
      if (lookahead == ' ') ADVANCE(9);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '>') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(120);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_label);
      if (lookahead == '-') ADVANCE(43);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == ' ' ||
          lookahead == '>') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != ']' &&
          lookahead != '|') ADVANCE(120);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == ' ') ADVANCE(4);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(122);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == ' ') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '[' &&
          lookahead != '{') ADVANCE(122);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_dest);
      if (lookahead == ' ') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(124);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_dest);
      if (lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != ']') ADVANCE(124);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_tag);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 44},
  [4] = {.lex_state = 44},
  [5] = {.lex_state = 12},
  [6] = {.lex_state = 12},
  [7] = {.lex_state = 12},
  [8] = {.lex_state = 12},
  [9] = {.lex_state = 12},
  [10] = {.lex_state = 44},
  [11] = {.lex_state = 44},
  [12] = {.lex_state = 44},
  [13] = {.lex_state = 44},
  [14] = {.lex_state = 44},
  [15] = {.lex_state = 44},
  [16] = {.lex_state = 44},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 36},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 36},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 36},
  [28] = {.lex_state = 36},
  [29] = {.lex_state = 36},
  [30] = {.lex_state = 19},
  [31] = {.lex_state = 36},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 19},
  [34] = {.lex_state = 36},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 36},
  [37] = {.lex_state = 19},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 26},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 19},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 26},
  [53] = {.lex_state = 26},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 26},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 37},
  [58] = {.lex_state = 19},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_LBRACK_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [sym_macro_name] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [aux_sym_string_token2] = ACTIONS(1),
    [aux_sym_string_token3] = ACTIONS(1),
    [sym_keyword_op] = ACTIONS(1),
    [sym__macro_word] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_story] = STATE(59),
    [sym_passage] = STATE(20),
    [sym_heading] = STATE(2),
    [aux_sym_story_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_COLON_COLON] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACKimg_LBRACK,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT_LT,
    ACTIONS(17), 1,
      sym_tag_name,
    ACTIONS(15), 3,
      sym_variable,
      sym_comment,
      sym_plain_text,
    STATE(42), 3,
      sym__body,
      sym_prose,
      sym_json,
    STATE(4), 6,
      sym__prose_part,
      sym_link,
      sym_image_link,
      sym_macro,
      sym_html_tag,
      aux_sym_prose_repeat1,
  [34] = 8,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(21), 1,
      anon_sym_COLON_COLON,
    ACTIONS(23), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(26), 1,
      anon_sym_LBRACKimg_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LT_LT,
    ACTIONS(35), 1,
      sym_tag_name,
    ACTIONS(32), 3,
      sym_variable,
      sym_comment,
      sym_plain_text,
    STATE(3), 6,
      sym__prose_part,
      sym_link,
      sym_image_link,
      sym_macro,
      sym_html_tag,
      aux_sym_prose_repeat1,
  [66] = 8,
    ACTIONS(7), 1,
      anon_sym_LBRACK_LBRACK,
    ACTIONS(9), 1,
      anon_sym_LBRACKimg_LBRACK,
    ACTIONS(13), 1,
      anon_sym_LT_LT,
    ACTIONS(17), 1,
      sym_tag_name,
    ACTIONS(38), 1,
      ts_builtin_sym_end,
    ACTIONS(40), 1,
      anon_sym_COLON_COLON,
    ACTIONS(42), 3,
      sym_variable,
      sym_comment,
      sym_plain_text,
    STATE(3), 6,
      sym__prose_part,
      sym_link,
      sym_image_link,
      sym_macro,
      sym_html_tag,
      aux_sym_prose_repeat1,
  [98] = 5,
    ACTIONS(44), 1,
      anon_sym_GT_GT,
    STATE(51), 1,
      sym_macro_body,
    STATE(7), 2,
      sym_string,
      aux_sym_macro_body_repeat1,
    ACTIONS(48), 3,
      aux_sym_string_token1,
      aux_sym_string_token2,
      aux_sym_string_token3,
    ACTIONS(46), 8,
      aux_sym_macro_body_token1,
      aux_sym_macro_body_token2,
      anon_sym_GT,
      anon_sym_QMARK,
      sym_variable,
      sym_keyword_op,
      sym__macro_word,
      sym_number,
  [124] = 5,
    ACTIONS(50), 1,
      anon_sym_GT_GT,
    STATE(56), 1,
      sym_macro_body,
    STATE(7), 2,
      sym_string,
      aux_sym_macro_body_repeat1,
    ACTIONS(48), 3,
      aux_sym_string_token1,
      aux_sym_string_token2,
      aux_sym_string_token3,
    ACTIONS(46), 8,
      aux_sym_macro_body_token1,
      aux_sym_macro_body_token2,
      anon_sym_GT,
      anon_sym_QMARK,
      sym_variable,
      sym_keyword_op,
      sym__macro_word,
      sym_number,
  [150] = 4,
    ACTIONS(52), 1,
      anon_sym_GT_GT,
    STATE(8), 2,
      sym_string,
      aux_sym_macro_body_repeat1,
    ACTIONS(48), 3,
      aux_sym_string_token1,
      aux_sym_string_token2,
      aux_sym_string_token3,
    ACTIONS(54), 8,
      aux_sym_macro_body_token1,
      aux_sym_macro_body_token2,
      anon_sym_GT,
      anon_sym_QMARK,
      sym_variable,
      sym_keyword_op,
      sym__macro_word,
      sym_number,
  [173] = 4,
    ACTIONS(56), 1,
      anon_sym_GT_GT,
    STATE(8), 2,
      sym_string,
      aux_sym_macro_body_repeat1,
    ACTIONS(61), 3,
      aux_sym_string_token1,
      aux_sym_string_token2,
      aux_sym_string_token3,
    ACTIONS(58), 8,
      aux_sym_macro_body_token1,
      aux_sym_macro_body_token2,
      anon_sym_GT,
      anon_sym_QMARK,
      sym_variable,
      sym_keyword_op,
      sym__macro_word,
      sym_number,
  [196] = 1,
    ACTIONS(64), 12,
      anon_sym_GT_GT,
      aux_sym_macro_body_token1,
      aux_sym_macro_body_token2,
      anon_sym_GT,
      anon_sym_QMARK,
      sym_variable,
      aux_sym_string_token1,
      aux_sym_string_token2,
      aux_sym_string_token3,
      sym_keyword_op,
      sym__macro_word,
      sym_number,
  [211] = 2,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [225] = 2,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [239] = 2,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [253] = 2,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [267] = 2,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [281] = 2,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [295] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 8,
      anon_sym_COLON_COLON,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [309] = 1,
    ACTIONS(94), 8,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [320] = 1,
    ACTIONS(96), 8,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [331] = 1,
    ACTIONS(98), 8,
      anon_sym_LBRACK_LBRACK,
      anon_sym_LBRACKimg_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_variable,
      sym_comment,
      sym_tag_name,
      sym_plain_text,
  [342] = 4,
    ACTIONS(5), 1,
      anon_sym_COLON_COLON,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_heading,
    STATE(21), 2,
      sym_passage,
      aux_sym_story_repeat1,
  [356] = 4,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      anon_sym_COLON_COLON,
    STATE(2), 1,
      sym_heading,
    STATE(21), 2,
      sym_passage,
      aux_sym_story_repeat1,
  [370] = 5,
    ACTIONS(107), 1,
      anon_sym_LF,
    ACTIONS(109), 1,
      anon_sym_LBRACK,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      sym_tags,
    STATE(49), 1,
      sym_inline_json,
  [386] = 4,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 1,
      aux_sym__json_part_token1,
    STATE(28), 1,
      aux_sym__json_part,
  [399] = 4,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    ACTIONS(123), 1,
      aux_sym__inline_json_part_token1,
    STATE(26), 1,
      aux_sym__inline_json_part,
  [412] = 4,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      aux_sym__json_part_token1,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      aux_sym__json_part,
  [425] = 4,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(130), 1,
      anon_sym_RBRACE,
    ACTIONS(132), 1,
      aux_sym__inline_json_part_token1,
    STATE(26), 1,
      aux_sym__inline_json_part,
  [438] = 4,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      aux_sym__json_part_token1,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(28), 1,
      aux_sym__json_part,
  [451] = 4,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    ACTIONS(142), 1,
      aux_sym__json_part_token1,
    STATE(28), 1,
      aux_sym__json_part,
  [464] = 2,
    ACTIONS(147), 1,
      aux_sym__json_part_token1,
    ACTIONS(145), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [472] = 3,
    ACTIONS(149), 1,
      anon_sym_RBRACK,
    ACTIONS(151), 1,
      sym_tag,
    STATE(37), 1,
      aux_sym_tags_repeat1,
  [482] = 3,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      aux_sym__json_part_token1,
    STATE(27), 1,
      aux_sym__json_part,
  [492] = 3,
    ACTIONS(119), 1,
      anon_sym_LBRACE,
    ACTIONS(155), 1,
      aux_sym__inline_json_part_token1,
    STATE(24), 1,
      aux_sym__inline_json_part,
  [502] = 3,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    ACTIONS(159), 1,
      sym_tag,
    STATE(30), 1,
      aux_sym_tags_repeat1,
  [512] = 3,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(161), 1,
      aux_sym__json_part_token1,
    STATE(23), 1,
      aux_sym__json_part,
  [522] = 3,
    ACTIONS(111), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_LF,
    STATE(45), 1,
      sym_inline_json,
  [532] = 3,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      aux_sym__json_part_token1,
    STATE(25), 1,
      aux_sym__json_part,
  [542] = 3,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    ACTIONS(169), 1,
      sym_tag,
    STATE(37), 1,
      aux_sym_tags_repeat1,
  [552] = 2,
    ACTIONS(174), 1,
      aux_sym__inline_json_part_token1,
    ACTIONS(172), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [560] = 1,
    ACTIONS(176), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [565] = 2,
    ACTIONS(178), 1,
      anon_sym_LF,
    ACTIONS(180), 1,
      anon_sym_LBRACE,
  [572] = 2,
    ACTIONS(182), 1,
      anon_sym_GT,
    ACTIONS(184), 1,
      sym_attributes,
  [579] = 1,
    ACTIONS(186), 2,
      ts_builtin_sym_end,
      anon_sym_COLON_COLON,
  [584] = 2,
    ACTIONS(188), 1,
      anon_sym_SLASH,
    ACTIONS(190), 1,
      sym_macro_name,
  [591] = 2,
    ACTIONS(192), 1,
      anon_sym_LF,
    ACTIONS(194), 1,
      anon_sym_LBRACE,
  [598] = 1,
    ACTIONS(196), 1,
      anon_sym_LF,
  [602] = 1,
    ACTIONS(198), 1,
      sym_dest,
  [606] = 1,
    ACTIONS(200), 1,
      sym_dest,
  [610] = 1,
    ACTIONS(202), 1,
      sym_label,
  [614] = 1,
    ACTIONS(163), 1,
      anon_sym_LF,
  [618] = 1,
    ACTIONS(204), 1,
      sym_separator,
  [622] = 1,
    ACTIONS(206), 1,
      anon_sym_GT_GT,
  [626] = 1,
    ACTIONS(208), 1,
      anon_sym_RBRACK_RBRACK,
  [630] = 1,
    ACTIONS(210), 1,
      sym_macro_name,
  [634] = 1,
    ACTIONS(212), 1,
      anon_sym_LF,
  [638] = 1,
    ACTIONS(214), 1,
      anon_sym_RBRACK_RBRACK,
  [642] = 1,
    ACTIONS(216), 1,
      anon_sym_GT_GT,
  [646] = 1,
    ACTIONS(218), 1,
      sym_name,
  [650] = 1,
    ACTIONS(220), 1,
      anon_sym_GT,
  [654] = 1,
    ACTIONS(222), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 98,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 150,
  [SMALL_STATE(8)] = 173,
  [SMALL_STATE(9)] = 196,
  [SMALL_STATE(10)] = 211,
  [SMALL_STATE(11)] = 225,
  [SMALL_STATE(12)] = 239,
  [SMALL_STATE(13)] = 253,
  [SMALL_STATE(14)] = 267,
  [SMALL_STATE(15)] = 281,
  [SMALL_STATE(16)] = 295,
  [SMALL_STATE(17)] = 309,
  [SMALL_STATE(18)] = 320,
  [SMALL_STATE(19)] = 331,
  [SMALL_STATE(20)] = 342,
  [SMALL_STATE(21)] = 356,
  [SMALL_STATE(22)] = 370,
  [SMALL_STATE(23)] = 386,
  [SMALL_STATE(24)] = 399,
  [SMALL_STATE(25)] = 412,
  [SMALL_STATE(26)] = 425,
  [SMALL_STATE(27)] = 438,
  [SMALL_STATE(28)] = 451,
  [SMALL_STATE(29)] = 464,
  [SMALL_STATE(30)] = 472,
  [SMALL_STATE(31)] = 482,
  [SMALL_STATE(32)] = 492,
  [SMALL_STATE(33)] = 502,
  [SMALL_STATE(34)] = 512,
  [SMALL_STATE(35)] = 522,
  [SMALL_STATE(36)] = 532,
  [SMALL_STATE(37)] = 542,
  [SMALL_STATE(38)] = 552,
  [SMALL_STATE(39)] = 560,
  [SMALL_STATE(40)] = 565,
  [SMALL_STATE(41)] = 572,
  [SMALL_STATE(42)] = 579,
  [SMALL_STATE(43)] = 584,
  [SMALL_STATE(44)] = 591,
  [SMALL_STATE(45)] = 598,
  [SMALL_STATE(46)] = 602,
  [SMALL_STATE(47)] = 606,
  [SMALL_STATE(48)] = 610,
  [SMALL_STATE(49)] = 614,
  [SMALL_STATE(50)] = 618,
  [SMALL_STATE(51)] = 622,
  [SMALL_STATE(52)] = 626,
  [SMALL_STATE(53)] = 630,
  [SMALL_STATE(54)] = 634,
  [SMALL_STATE(55)] = 638,
  [SMALL_STATE(56)] = 642,
  [SMALL_STATE(57)] = 646,
  [SMALL_STATE(58)] = 650,
  [SMALL_STATE(59)] = 654,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_story, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prose_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prose, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prose, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_body, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_macro_body_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_macro_body_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_tag, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_tag, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_image_link, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_image_link, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_tag, 3, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_tag, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_link, 5, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_link, 5, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 4, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_heading, 5, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_story, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_story_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_story_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inline_json_part, 2, 0, 0), SHIFT_REPEAT(31),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline_json_part, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inline_json_part, 2, 0, 0), SHIFT_REPEAT(26),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__json_part, 2, 0, 0), SHIFT_REPEAT(36),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__json_part, 2, 0, 0),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__json_part, 2, 0, 0), SHIFT_REPEAT(28),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__json_part, 3, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__json_part, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tags_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__inline_json_part, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inline_json_part, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_passage, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tags, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tags, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_json, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [222] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_twee(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "twee",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
